name: Generate snake animation

on:
  push:
      branches:
        - main
  schedule:
    - cron: "0 0 * * *"   # Chạy vào 0 giờ mỗi ngày
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=purple&color_dots=#e0e0e0,#a0c4ff,#6ea8fe,#3a7bd5,#1e3a8a

      - name: Deploy to branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}